name: Test films Endpoint

on: [push, pull_request]

jobs:
  test-films:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run Test films
        run: npm test -- -t "Deve visualizar informações de cadastro, quando buscar por uma pessoa existente"